### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by VioletXe** [Finnerex/MissileTurret#1]
Code - Unlike mines and turrets we can't see or disable this through the minimap or through mods like Scannable Codes.

Activation Light - Turrets and mines all have a glow that alerts players to their existence in the dark making more the player's fault if they die. In its current state the light isn't really needed since it's easy to just sidestep the rocket, but a threat should still have some warning.

Missile Speed - It should probably be much faster. Rather than a rocket, the missile feels like someone throwing a rock through molasses. I assume this was done to provide players time to run away, but it makes the turret a complete non threat to the degree I could matrix past it down a long hallway. The Activation Light and brief pause before firing turrets have, combined with the ability to disable them, makes the vanilla ones balanced for their killing power.

Love the mod though, was looking for something like this for a LONG time now. <3

**Comment by Finnerex** [comment]
Thanks for the suggestions! Configurable acceleration should be coming your way shortly. Adding the activation light shouldn't take long either. As for the ability to deactivate them, it could be complicated, I still need to figure this one out.
