### ISSUE TITLE
More of a question!  

### ISSUE THREAD

**Issue by Aono100** [Finnerex/MissileTurret#2]
For the blast radius, i was wonder what was the max number to make it bigger? because i wanted to make sure if someone screws up by being next to a turret and it goes off. everyone ( or most everyone) inside the building gets blow up . Lol

**Comment by Finnerex** [comment]
I don't think there is a maximum on the blast radius. I do not quite know if it could kill everyone in the building as I am calling a game function that might not allow for this. If I had to guess, the explosion probably can't kill people through walls.

**Comment by Aono100** [comment]
ah! as i guessed. thank you for your reply! and thank you for the funny mod, too! haha have a wonderful day!  <3
